### ISSUE TITLE
latest version SNOW plugin 

### ISSUE THREAD

**Issue by willipwolf** [archi-contribs/snow-import-plugin#12]
Hi, for some reason it seems the Specialization plugin is here instead of the latest SNOW plugin?

**Comment by herve91** [comment]
you are right, I copied the specialization plugin to this project by mistake.

Please note that the jar file is correct, only the archiplugin file was wrong (and both files can be used to install the plugin)

I removed the wrong archiplugin file and uploaded the correct one. Thanks for reporting this anomaly.
