### ISSUE TITLE
Plugin not working with Archi 4.8.1

### ISSUE THREAD

**Issue by scotti526** [archi-contribs/snow-import-plugin#13]
I have Archi 4.8.1 installed with the Database export plugin. I tired to add the SNOW plugin (downloaded the org.archicontribs.servicenow_1.7.2.archiplugin file and installed through help>manage plugins). I get a response that "org.archicontribs.servicenow_1.7.2.archiplugin - is not an Archi Plug-in". I have downloaded the file twice to make sure It wasn't corrupt or a bad download.

**Comment by herve91** [comment]
The file is definitively an archiplugin file, I just tested again. Please verify that the file you downloaded is 14 469 865 bytes.

if you unzip the file, it should contain the jar file plus an empty file called "archi-plugin"

The easiest way to download it is to click on the file name, then click on the download button.

![image](https://user-images.githubusercontent.com/9281982/111163182-3033e880-859d-11eb-9dbd-9281b96010e8.png)

**Comment by scotti526** [comment]
Thanks, that was it, I must have downloaded HTML or something else.
