### ISSUE TITLE
Is it possible to add an explicit license?

### ISSUE THREAD

**Issue by jbsarrodie** [archi-contribs/snow-import-plugin#14]
Hi Hervé,

Some colleagues would like to use this plugin, but I can't find any real license in this repo (there is a license file which is almost empty). Would it be possible for you to add an explicit license, such as the MIT one that we use for all Archi related work. If needed, here [an example of our license file](https://github.com/archi-contribs/fontloader-plugin/blob/master/LICENSE.txt).

Regards,

JB

**Comment by herve91** [comment]
Hi JB,

Yes, sure. My apologies not having this done before ;-)

Please tell your colleagues this plugin has been the first I developed and therefore does not have any graphical interface. The configuration is done through a configuration file.

Best regards
Hervé

**Comment by jbsarrodie** [comment]
Hi Hervé,

Thank you.

Don't worry, they know the plugin is provided "as is" and they will have to configure it by hand.

Regards,

JB

**Comment by herve91** [comment]
I close the case.
