### ISSUE TITLE
Add filter on URL of import of relationships - useful for large sets

### ISSUE THREAD

**Issue by Manj75** [archi-contribs/snow-import-plugin#5]
There is already a filter option for Archi elements and not currently available for Relationships.  This request is raised for the ability to specify a "filter" property which is added to the "sysparm_query" part of the request.

E.g.  URL comprises of: sysparm_query=x_snsab_snow_sam_i_snow_checksumISNOTEMPTY

Also, there is no instructions on how to specify filters even of Archi elements and would be useful to have this documented in the ini file, as the filter can be many variations.  Also can I specify multiple filters and if so how, some examples would be helpful.

**Comment by herve91** [comment]
Will do it

**Comment by Manj75** [comment]
Thanks - do you have an approximation of when the next release will be available.

**Comment by herve91** [comment]
today if everything goes well :-)

**Comment by herve91** [comment]
version 1.7 released few minutes ago.

Please note that the file structure changed a bit: you need to add a "snow_table" property now.

This allow to parse several times the same ServiceNow table with a different filter.
